name: Show Composite Action Usage
description: We are doing this to practice

inputs:
  message:
    description: Message to display
    required: false
    default: "Hello from composite action made by Kourosh!"

runs:
  using: composite
  steps:
    - name: Show custom message
      run: |
        echo "${{ inputs.message }}"

    - name: Show GitHub context
      run: |
        echo "Hello world from Kourosh!"
        echo "How you doing lads?"