name: Show Composite Action Usage
description: We are doing this to practice

runs:
  using: composite
  steps:
    - name: Show GitHub context
      shell: bash
      ses: actions/checkout@v2
      run: |
        echo "Hello world from Kourosh!"
        echo "How you doing lads?"